# Generated by Django 4.2.1 on 2023-05-29 18:27

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('reg_number', models.CharField(max_length=10)),
                ('owner_name', models.CharField(max_length=100)),
                ('owner_email', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('skipper_name', models.CharField(max_length=150)),
                ('skipper_email', models.EmailField(blank=True, max_length=254)),
                ('skipper_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('boat_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boatski.boat')),
            ],
        ),
        migrations.CreateModel(
            name='DailyRentalPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('daily_rent', models.PositiveIntegerField()),
                ('available', models.BooleanField(default=True)),
                ('boat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boatski.boat')),
            ],
            options={
                'unique_together': {('date', 'boat_id')},
            },
        ),
    ]
