# Generated by Django 4.2.1 on 2023-05-28 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boatski', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='boat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boatski.boat'),
        ),
    ]
