# Generated by Django 4.2.1 on 2023-05-28 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boatski', '0002_booking_boat'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_price', models.PositiveIntegerField(blank=True)),
                ('boat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boatski.boat')),
            ],
        ),
    ]
