# Generated by Django 4.2.1 on 2023-05-28 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boatski', '0003_rentalprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='boat',
            new_name='boat_id',
        ),
    ]
