# Generated by Django 4.2.1 on 2023-05-28 18:59

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('boatski', '0005_rentalprice_bookings_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='skipper_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Contact phone number', max_length=128, region=None),
        ),
    ]
