# Generated by Django 4.2.1 on 2023-05-28 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boatski', '0007_alter_booking_skipper_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentalprice',
            old_name='boat',
            new_name='boat_id',
        ),
    ]
